### ISSUE TITLE
I have no idea what I'm doing

### ISSUE THREAD

**Issue by BAXA6** [OpenGM8/GM8Decompiler#16]
Hello!
As the title suggests, I explicitly downloaded Rust to use this tool, and am very, utterly lost.
After using cargo build in console, I get this:

error: failed to run custom build command for `gm8decompiler v2.1.1 (C:\Users\<User>\Desktop\GM8Decompiler-master)`

Caused by:
  process didn't exit successfully: `C:\Users\<User>\Desktop\GM8Decompiler-master\target\debug\build\gm8decompiler-13460346f50a5470\build-script-build` (exit code: 1)
  --- stdout
  cargo:rustc-env=BUILD_DATE=2021/10/12

  --- stderr
  Error: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  
  I had a minor error of cmake not being found by the program, which a bit of Googling helped with, and I've reinstalled Rust.
  The error makes no sense to me, what am I missing?
Thank you very much for your help

**Comment by viriuwu** [comment]
Could it be you don't have `git` in your PATH? I see the error originates from the build script, and I think that error looks like what happens when you run an unknown command.
https://github.com/OpenGMK/GM8Decompiler/blob/452a89b34eb02ed3f93aa3656df93f3535e59992/build.rs#L10
Seeing you're on Windows, you can download a pre-built release from the releases page, if you'd like:
https://github.com/OpenGMK/GM8Decompiler/releases/tag/v2.1.1

**Comment by viriuwu** [comment]
No problem. For future reference, the development of this tool was merged to the central unified project because it's much easier for us to share the code that way: https://github.com/OpenGMK/OpenGMK

New releases will still be available here, though. We should update the README to indicate this, sorry about that. Thank you for using our tool.
