### ISSUE TITLE
rva 0x

### ISSUE THREAD

**Issue by kaan5739** [OpenGM8/GM8Decompiler#23]
i get this error what to do?

**Comment by Adamcake** [comment]
What are you doing that causes the error?

Is "rva 0x" the whole message?

**Comment by kaan5739** [comment]
No its rva 0xsomerandomletters it closes fast so i cant see it but it looks like that

**Comment by kaan5739** [comment]
![Ekran görüntüsü 2023-04-20 204240](https://user-images.githubusercontent.com/109537520/233446059-3e6d5050-03a0-420d-bd6f-86600f50bbc4.png)

**Comment by Adamcake** [comment]
That just means it wasn't able to recover the exe icon for some reason, but it should still produce a GMK. If not then that means something else is going wrong after that. Is there a download link for this game you can give me?

FYI, running the app from the command line will let you see the output without the console closing after it exits.

**Comment by kaan5739** [comment]
here
https://amateratmg.itch.io/five-nights-in-anime-3 (dont judge me)
also i cant enter here very often so sorry

**Comment by kaan5739** [comment]
i kinda changed the icon of the exe and when i try again it opens , says nothing and crashes

**Comment by Adamcake** [comment]
I downloaded "FNIA 3 11-07-2018.exe" and looked inside. I'm not sure if this is actually the game or just an installer, since the executable part of the file is is very small (just under 400 KB) with a ton of extra data. I also can't get it to run using wine. Either way, I'm not sure what was used to make this exe, but it definitely wasn't any version of GameMaker.

**Comment by kaan5739** [comment]
i want to decompile this how can i do that?

**Comment by Adamcake** [comment]
Alright I asked the other devs, this appears to be made with the MultiMedia Fusion engine. You'd need an MMF decompiler for it. A quick search online suggests [CTFAK2](https://github.com/CTFAK/CTFAK2.0) as one option.

I'm not able to help any further with this, since the game isn't a GMK and I don't have any knowledge of MMF. Best of luck in recovering the game assets.

**Comment by kaan5739** [comment]
wow i didnt think u would go this far thanks!!
