### ISSUE TITLE
Parsing error: Invalid EXE header

### ISSUE THREAD

**Issue by Moterius** [OpenGM8/GM8Decompiler#27]
Context, I'm trying to look at the assets for [The Void Rains Upon Her Heart](https://gamemaker.io/en/showcase/the-void-rains-upon-her-heart).

**Comment by Adamcake** [comment]
Since this game is a paid download I can't verify for myself, but there are only two cases which would create an InvalidExeHeader error: the file you're trying to decompile either is not a valid .exe file, or is not i386 architecture.

(Relevant code: https://github.com/OpenGMK/OpenGMK/blob/ebaa4d125758f6f65ff0deebbd4ab3fd5e817314/gm8exe/src/reader.rs#L79-L91 )

I did some searching on this game to try to find out its engine. Steam's metadata lists the engine as just "GameMaker", but a [fan wiki](https://the-void-rains-upon-her-heart.fandom.com/wiki/The_Void_Rains_Upon_Her_Heart) claims the engine is GameMaker Studio 2. This project only targets the classic GameMaker versions before Studio, so it sounds like you need to look for a GameMaker Studio 2 decompiler. I think [UndertaleModTool](https://github.com/krzys-h/UndertaleModTool) would be your best shot. Best of luck.
